# Site settings
title: Codenize.tools
email: sgwr_dts@yahoo.co.jp
#description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codenize.tools" # the base hostname & protocol for your site
twitter_username: sgwr_dts
github_username:  winebarrel

# Build settings
markdown: kramdown
